### ISSUE TITLE
Exercise1 Task 2 Error - cant move forward to step3

### ISSUE THREAD

**Issue by ondemand2002** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#17]
hi,

When I get to the step2 of Exercise1/Task2, I got error message, which shows "method not found" and can't move forward to Step3, even I click the next button at Step 2.

Detailed screen shot are attached.

Could you give some suggestions to fix this error?

Thanks.
![Task 2-Create external table from CSV files-error-1](https://user-images.githubusercontent.com/50772841/91045795-c4b71780-e65a-11ea-9599-e430f329a34d.jpg)
![Task 2-Create external table from CSV files-error-2](https://user-images.githubusercontent.com/50772841/91045799-c5e84480-e65a-11ea-8a30-a79a3ed4b211.jpg)

**Comment by feaselkl** [comment]
Please make sure you have the latest version of Azure Data Studio and the latest version of the Data Virtualization extension installed.  The latest version of the Data Virtualization extension is 1.8.0.  You may see a "Reload Required" message on the extension details; if so, select it and restart Azure Data Studio.

![DataVirtualizationVersion](https://user-images.githubusercontent.com/1330589/91103244-0df66f80-e639-11ea-8ecf-8444f28767a2.png)

Once the Data Virtualization extension is up to date, the **Method not found** error message should go away and you should see a preview of the data.

Please let me know if you have any issues after updating to the latest version of the extension.

**Comment by ondemand2002** [comment]
Error fixed by following you suggestion. Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
