### ISSUE TITLE
Issue in Installing SQL Server 2019 Big Data clusters

### ISSUE THREAD

**Issue by amalgireesh** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#2]
1.In Before the HOL,[Task 3](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Modernizing%20Data%20Analytics%20with%20SQL%20Server%202019.md#Task-3-Install-SQL-Server-2019-Big-Data-clusters),step 5, the link given to download the python script for creating an AKS service and then deploying a SQL Server 2019 big data cluster to AKS is not available.

![python_link](https://user-images.githubusercontent.com/48020356/64171351-1118ae80-ce70-11e9-8e4c-438937aaf09d.png)
And its redirected to:
![error404](https://user-images.githubusercontent.com/48020356/64171654-c9deed80-ce70-11e9-9508-c8e6bdbc71cd.PNG)
2.But in the resource folder [deploy-sql-big-data-aks.py](https://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/deploy-sql-big-data-aks.py) is available.
3.Tried deploying the python script but taking unexpected time and cluster is getting failed invariably.
Can you please check ,fix this **ASAP**.

Thanks,
Amal Gireesh

**Comment by amalgireesh** [comment]
Have tried to deploy the python script using CLI but again getting error as following;
![error5](https://user-images.githubusercontent.com/48020356/64547714-d1a80180-d34a-11e9-875b-923d62e8b7c8.PNG)
Can you please check fix **ASAP**
Thanks.

**Comment by akn9050** [comment]
any update on this

**Comment by joelhulen** [comment]
Sorry for the late reply, @akn9050. This lab is due for a test/fix and the content author assigned to this will address this and other issues this coming week. Since SQL Server 2019 BDC is pre-release, a lot of tooling used to create and manage the instances routinely undergo breaking changes. Hopefully, with the upcoming GA release, things will stabilize soon.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved
