### ISSUE TITLE
Could not open a connection to SQL Server

### ISSUE THREAD

**Issue by kinghendrix10** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#20]
Hello,

I was trying to use the External Table Wizard in Azure Data Studio to connect to the external Azure SQL Database
 
I used the following code 
 ```
 CREATE EXTERNAL DATA SOURCE SQLServerInstance WITH
  (
    LOCATION = 'sqlserver://<YOUR_AZURE_SERVER_NAME>.database.windows.net',
    -- PUSHDOWN = ON | OFF,
    CREDENTIAL = SQLCred,
    CONNECTION_OPTIONS='Database=wwi_commerce' 
  );
END
GO

IF (OBJECT_ID('dbo.Reviews') IS NULL)
BEGIN
  CREATE EXTERNAL TABLE dbo.Reviews
  (
    [product_id] [bigint] NOT NULL,
    [customer_id] [bigint] NOT NULL,
    [review] [nvarchar](1000) NOT NULL,
    [date_added] [datetime] NOT NULL
  )
  WITH
  (
    LOCATION='wwi_commerce.dbo.Reviews',
    DATA_SOURCE=SqlServerInstance
  );
END
GO
```
but got the following error

> Msg 105082, Level 16, State 1, Line 52 105082;Generic ODBC error: [Microsoft][ODBC Driver 17 for SQL Server]Named Pipes Provider: Could not open a connection to SQL Server [2]. Additional error <2>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired, SqlState: HYT00, NativeError: 0 Additional error <3>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute, SqlState: 01S00, NativeError: 0 Additional error <4>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to, SqlState: 08001, NativeError: 2.

I can make out that it's likely that I got the SQL server name wrong but I am not sure because I tried the name I used when setting up the server and it still gave me this error

Is there a way of explicitly getting the MS_AZURE_SERVER_NAME or am I missing something else?

Thanks

**Comment by Grv-Singh** [comment]
It seems to be 'INIT-sql-mod-data', see [here](urlhttps://github.com/microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019/blob/master/Hands-on%20lab/Resources/template.json#L13)

**Comment by kinghendrix10** [comment]
I have problems using INIT-sql-mod-data as my server name when I was creating the resource group. I tried using the server name that I used when creating my server  'res-sql-mod-data' but still got the same error

**Comment by feaselkl** [comment]
Please try using the IP address associated with the SQL Server instance, which you get at the end of the notebook.  You will not be able to use the server name unless you change your hosts file to provide a redirect.  The name `res-sql-mod-data` is not a routable address; it is used within Azure to identify the resource.

**Comment by kinghendrix10** [comment]
I tried using the IP address associated with the SQL Server instance(master-svc-external) but got the same error

**Comment by feaselkl** [comment]
Are you trying the 10.0.x.x IP address or the other one?  If you are trying the 10.0.x.x IP address, it won't be routable.

**Comment by kinghendrix10** [comment]
No... The 52.x.x.x one

**Comment by feaselkl** [comment]
Sorry, I misread the question and was thinking you were having trouble connecting to the master instance of the Big Data Cluster, but it sounds like you're having trouble connecting from the master instance to Azure SQL Database.

If you are having trouble connecting from the master instance of the Big Data Cluster to the Azure SQL Database which you've named `res-sql-mod-data`, the most likely culprit is that the server firewall is blocking access.  Please double-check that you've gone through Task 5, specifically the part about allowing access to Azure services:

1. Navigate to the Azure portal.
2. Select the WWI_Commerce database resource.
3. On the Overview pane, select Set server firewall to add your IP address.
4. Select + Add client IP to automatically add your system's IP address, and make sure **Allow access to Azure services is set to ON**.
5. Select Save to apply your changes.

Also, try connecting directly to the Azure SQL Database instance from SQL Server Management Studio or Azure Data Studio using `res-sql-mod-data.database.windows.net` to ensure that you can connect to it from your VM.

**Comment by kinghendrix10** [comment]
I tried that already and retried that again. I can query the SQL DB tables from SQL Server Management Studio or Azure Data Studio but can't seem to create the external table because I keep getting the connection string error

**Comment by feaselkl** [comment]
One other thing to try would be to add the SQL Server master instance's IP address to the firewall rules for Azure SQL Database.  If that doesn't work, you could try re-creating the Azure SQL Database or skipping the step.  There is another example of using an external table against HDFS, and reviews are used in one query.  If you do skip this step, the query to update would be Task 3 Step 1, removing the join to dbo.Reviews and the two review columns.

**Comment by feaselkl** [comment]
I just walked through the steps on a brand new setup, running the before the lab steps and then Task 1, up to step 3 of the hands-on lab and created an external data source successfully.

In this example, the VM is 52.152.233.87 and the SQL Database is kf-sql-mod-data.database.windows.net.  The SQL Server master instance is at 52.188.79.176.

Server name from Azure SQL Database:
![image](https://user-images.githubusercontent.com/1330589/95276649-cfe49200-0819-11eb-9aee-9c4314968123.png)

Server firewall settings from Azure SQL Database:
![image](https://user-images.githubusercontent.com/1330589/95276697-f0ace780-0819-11eb-89fc-cc629b94a5bb.png)

The client IP address rule will let us connect directly to Azure SQL Database from Azure Data Studio or SQL Server Management Studio.  Enabling `Allow Azure services and resources to access this server` will let the Big Data Cluster master instance connect.

Doing these results in successful creation of the external data source:
![image](https://user-images.githubusercontent.com/1330589/95276807-35d11980-081a-11eb-8e91-28a5a867a250.png)

At this point, I'm not sure I can do much other than to suggest checking your settings and ensuring that all steps have been followed correctly.  You might need to start over, destroying the resource groups and running through the Before the HOL steps again.

**Comment by bmerchant96** [comment]
I literally exhausted all of my credits fixing this issue 😥 and now I need a new credit card😥 to make a new account where can I get those things now and plus I overused the credits and now I am in extra 200$ debt 😪 because lucky Azure doesn't have real-time cost billing updates and I thought I am "ok" but it was already too late to stop using resources because I have already crossed the limit and the dashboard got updated very late   @feaselkl @feaselkl
