### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver17 for SQL Server : Login failed for user 'admin'

### ISSUE THREAD

**Issue by gympohnpimol** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#21]
Hi, guys
I got a problem when deploying task4 #3. While running the script named bootstrap-sample-db.cmd on vm, I got the error as a figure below 😔😢

<img width="979" alt="Screen Shot 2020-10-15 at 19 03 17" src="https://user-images.githubusercontent.com/56881546/96110509-eb872100-0f1a-11eb-8797-0aed01fad3bf.png">

Could you please explain to me how to fix this problem?
Thanks

**Comment by feaselkl** [comment]
Please confirm the following.

First, are you running the bootstrap command like this?

Here is a sample call.  Suppose the external IP address for connection to SQL Server is 52.170.174.25 and the external IP address for Knox is 52.191.85.30.

`bootstrap-sample-db.cmd mssql-cluster 52.170.174.25 <password> 52.191.85.30 <password> --install-extra-samples`

It's hard to read based on what's blacked out, but I see a reference to `C:/temp` which the instructions in step 3 do not call for.

Second, are you using the correct password?  When spinning up the Big Data Cluster, the same password is set for SQL Server and Knox.  It's hard to tell if the blacked-out section between the IP address and `C:/temp` is one long string or two strings.  If it's two and your password has a space in it, you could try putting quotation marks around the password or use a password without spaces.  Are you able to connect to the SQL Server master instance with that same password?

**Comment by gympohnpimol** [comment]
Thank you for you information.
After I did all steps as per your advice, I still stuck in this task as follows. 

<img width="971" alt="Screen Shot 2020-10-15 at 23 58 17" src="https://user-images.githubusercontent.com/56881546/96147892-b1317a00-0f42-11eb-9f2d-5b2274dcd2da.png">

**Comment by feaselkl** [comment]
That new error, that no connection could be made, indicates that the server is unavailable, whether due to a firewall rule or the Kubernetes cluster having shut down.  Are you able to connect to the SQL Server host on port 31433 using a tool like Azure Data Studio or SQL Server Management Studio from the machine you're where running the bootstrap command?

**Comment by timahenning** [comment]
@gympohnpimol Please open a new issue for the No connection error.  We are closing this issue as Kevin has resolved the original admin user error.

Tim
