### ISSUE TITLE
Error from server (NotFound): pods "master-0" not found

### ISSUE THREAD

**Issue by gympohnpimol** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#22]
Hello all,
I got an error while running bootstrap as ''Error from server (NotFound): pods "master-0" not found"
could you please tell me how to fix this error? Thanks
![Screenshot 2020-11-05 001455](https://user-images.githubusercontent.com/56881546/98129186-2f5abe00-1efc-11eb-861f-7a9b967c7f7a.png)

**Comment by gympohnpimol** [comment]
When I try to deploy the database on macos(catalina), I got the error of Microsoft ODBC Driver 17 for SQL Server as attachment.
I am not sure which way is easy for do this step between making on window or mac. I have done it by following the link https://docs.microsoft.com/th-th/sql/big-data-cluster/tutorial-load-sample-data?view=sqlallproducts-allversions

<img width="569" alt="Screen Shot 2020-11-05 at 4 22 37" src="https://user-images.githubusercontent.com/56881546/98158881-fda71e80-1f1e-11eb-8777-f5eb90eb776d.png">

Best regard

**Comment by feaselkl** [comment]
When you tried it on MacOS, you didn't include the SQL Server administrative password (which looks like in your example above is `1234_internS`.  But I will say that the lab intends you to run these scripts from the VM we set up when you load template.json.  That's a Windows VM and has things set up.

Based on the error in the first message, it looks like perhaps the Big Data Cluster did not deploy successfully or that the IP address you have used isn't the right one for the SQL Server master instance.  Try running `kubectl get svc -n <your-big-data-cluster-name>` to get the external IP addresses for `master-svc-external` and `gateway-svc-external`.  If those are in fact 52.191.237.191 and 52.191.238.60, respectively, the easiest route would probably be to tear down the Big Data Cluster and start again from Task 3.

**Comment by timahenning** [comment]
Hi @gympohnpimol,

Is this issue done?  It has been 7 days.
