### ISSUE TITLE
Issues in Lab.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Modernizing-Data-Analytics-with-SQL-Server-2019#7]
Please find the issues mentioned below 
**Before Hands on Lab:-** 
Task 4, item 5, in the script bootstrap-sample-db.cmd, line 42 should read "set SQLCMDUSER=admin" rather than sa and Lines 100 and 106 need a change from -Usa to -Uadmin although -U %SQLCMDUSER% would probably be better.

**HOL**:- 
 **Exercise 1: Using data virtualization** > Task 1: Create external table from Azure SQL Database - the first 2 objects in the script already exist.

Started executing query at Line 1
Msg 15578, Level 16, State 1, Line 1
There is already a master key in the database. Please drop it before performing this statement.
Started executing query at Line 3
Msg 15530, Level 16, State 1, Line 7
The credential with name "SQLCred" already exists.

**Exercise 1: Using data virtualization** > Task 1: Create external table from Azure SQL Database - the SQL script creates a table called SQLReviews but that is the only place that name is used, breaking the unified query in Task 3.

****Exercise 6** > Task 2 > item 7:** 
While Restarting the cluster the second command is not working  **supervisorctl restart mssql**, it should be** supervisorctl restart mssql-server**

**Comment by timahenning** [comment]
We have an upcoming test and set of fixes coming up this week.  Ike will review and check for this issue.

Tim

**Comment by sumitmalik51** [comment]
Hi @timahenning , is there have any update regarding the issue?

**Comment by timahenning** [comment]
We are close to having the fix released soon. Other team members are finishing up their comments and reviews first.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with December update merge.
